### ISSUE TITLE
New release with new name?

### ISSUE THREAD

**Issue by reedy** [php-parallel-lint/PHP-Var-Dump-Check#1]
Can you tag a new release that uses the packages from the php-parallel-lint organization/vendor? Thanks!

Same as php-parallel-lint/PHP-Console-Highlighter#1

**Comment by grogy** [comment]
Hello - it's here :-) https://github.com/php-parallel-lint/PHP-Var-Dump-Check/releases/tag/v0.4

**Comment by reedy** [comment]
Thanks!
