### ISSUE TITLE
Add --custom-function parameter to check

### ISSUE THREAD

**Issue by umutphp** [php-parallel-lint/PHP-Var-Dump-Check#5]
In one of the projects that I have been working for a while, there are some legacy custom dump functions created and used frequently by the team. A sample function is;

`function pre_dump( $var ) { 
    echo '<pre>'; 
    var_dump( $var ); 
    echo '</pre>'; 
}
`
The check tool can not find the usage of such kind of functions. A sample usage might be;

`$ ./vendor/bin/var-dump-check --no-colors --tracy --custom-function pre_dump,echo_dump .`

**Comment by grogy** [comment]
Hello,

it makes me sense. Thanks for PR, I will review it

**Comment by grogy** [comment]
It looks very good. You have some comments in PR. This issue i close, because PR will be merged. Thank you
